# Generated by Django 5.1.1 on 2024-09-18 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transaction', to='payment.paymentaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='account_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('suspended', 'suspended')], max_length=10),
        ),
    ]
