# Generated by Django 5.1.1 on 2024-09-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_transaction_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sender_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Transactiontype',
        ),
        migrations.DeleteModel(
            name='PaymentAccount',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
